# "org" ensures this Service is used with the correct Serverless Framework Access Key.
#org: scortema
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: backend-node-challenge
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend-node-challenge

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/server/routes.handler
    events:
      - httpApi: "*"
    environment:
      MONGODB_URI: ${ssm:/aws/reference/secretsmanager/taxdown/mongodb}

plugins:
  - serverless-offline
