services:

  Shared.MongoConfigFactory:
    class: '../../contexts/Shared/infrastructure/persistence/mongo/MongoConfigFactory'
    lazy: true

  Shared.MongoConfig:
    factory:
      class: '@Shared.MongoConfigFactory'
      method: 'createConfig'
    lazy: true

  Shared.domain.EventBus:
    class: '../../contexts/Shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus'
    arguments: []
    lazy: true

  Shared.MongoClientFactory:
    class: '../../contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory'
    lazy: true

  Shared.MongoClient:
    factory:
      class: '@Shared.MongoClientFactory'
      method: 'createClient'
    arguments:
      - 'shop'
      - '@Shared.MongoConfig'
    lazy: true
